"""
Train sklearn LogisticRegression on synthetic Bridge risk data,
then export coefficients for the TypeScript runtime.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    roc_auc_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

FEATURE_COLS = [
    "log_amount",
    "velocity_10m",
    "high_value",
    "very_high_value",
    "suspicious_merchant",
    "off_hours",
    "new_device",
    "ip_risk",
    "non_ng_context",
]

# Map CSV / sklearn feature names → TypeScript WEIGHTS keys
TS_KEYS = [
    "logAmount",
    "velocity10m",
    "highValue",
    "veryHighValue",
    "suspiciousMerchant",
    "offHours",
    "newDevice",
    "ipRisk",
    "nonNgContext",
]


def load_xy(path: Path) -> tuple[np.ndarray, np.ndarray]:
    df = pd.read_csv(path)
    x = df[FEATURE_COLS].to_numpy(dtype=float)
    y = df["is_risky"].to_numpy(dtype=int)
    return x, y


def coefficients_in_original_space(pipe: Pipeline) -> tuple[float, dict[str, float]]:
    """
    Undo StandardScaler so TS can score raw features (same as extractFeatures).
    For logistic: z = w_scaled @ ((x - mean) / scale) + b_scaled
               = (w_scaled / scale) @ x + (b_scaled - (w_scaled / scale) @ mean)
    """
    scaler: StandardScaler = pipe.named_steps["scaler"]
    clf: LogisticRegression = pipe.named_steps["clf"]
    w_scaled = clf.coef_.ravel()
    b_scaled = float(clf.intercept_[0])
    scale = scaler.scale_
    mean = scaler.mean_

    w_raw = w_scaled / scale
    b_raw = b_scaled - float(np.dot(w_raw, mean))

    weights = {key: round(float(w), 6) for key, w in zip(TS_KEYS, w_raw)}
    return round(b_raw, 6), weights


def write_ts_weights(path: Path, model_id: str, bias: float, weights: dict[str, float]) -> None:
    lines = [
        "/** Auto-generated by python/train.py — do not edit by hand. */",
        f'export const TRAINED_MODEL_ID = "{model_id}" as const;',
        "",
        "export const TRAINED_WEIGHTS = {",
        f"  bias: {bias},",
    ]
    for key in TS_KEYS:
        lines.append(f"  {key}: {weights[key]},")
    lines.append("} as const;")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Train Bridge risk logistic model")
    parser.add_argument("--train", type=Path, default=root / "data" / "synthetic_risk_train.csv")
    parser.add_argument("--test", type=Path, default=root / "data" / "synthetic_risk_test.csv")
    parser.add_argument("--artifacts", type=Path, default=root / "artifacts")
    parser.add_argument("--ts-out", type=Path, default=root / "src" / "trainedWeights.ts")
    parser.add_argument("--model-id", type=str, default="bridge-risk-logit-sklearn-v1")
    args = parser.parse_args()

    if not args.train.exists() or not args.test.exists():
        raise SystemExit(
            f"Missing data. Run: python python/generate_data.py\n"
            f"Expected {args.train} and {args.test}"
        )

    x_train, y_train = load_xy(args.train)
    x_test, y_test = load_xy(args.test)

    pipe = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            (
                "clf",
                LogisticRegression(
                    max_iter=2000,
                    class_weight="balanced",
                    C=5.0,
                    random_state=42,
                ),
            ),
        ]
    )
    pipe.fit(x_train, y_train)

    proba = pipe.predict_proba(x_test)[:, 1]
    pred = (proba >= 0.5).astype(int)
    metrics = {
        "model_id": args.model_id,
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "n_train": int(len(y_train)),
        "n_test": int(len(y_test)),
        "accuracy": round(float(accuracy_score(y_test, pred)), 4),
        "roc_auc": round(float(roc_auc_score(y_test, proba)), 4),
        "positive_rate_train": round(float(y_train.mean()), 4),
        "positive_rate_test": round(float(y_test.mean()), 4),
        "classification_report": classification_report(
            y_test, pred, target_names=["legit", "risky"], output_dict=True
        ),
    }

    bias, weights = coefficients_in_original_space(pipe)
    payload = {
        "model_id": args.model_id,
        "algorithm": "sklearn.linear_model.LogisticRegression",
        "features": FEATURE_COLS,
        "bias": bias,
        "weights": weights,
        "thresholds": {"deny": 0.78, "review": 0.45},
        "metrics": {
            "accuracy": metrics["accuracy"],
            "roc_auc": metrics["roc_auc"],
        },
        "data_note": "Trained on synthetic labels only — not production Wema fraud data.",
    }

    args.artifacts.mkdir(parents=True, exist_ok=True)
    weights_path = args.artifacts / "weights.json"
    metrics_path = args.artifacts / "metrics.json"
    weights_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    write_ts_weights(args.ts_out, args.model_id, bias, weights)

    print(json.dumps({"accuracy": metrics["accuracy"], "roc_auc": metrics["roc_auc"], "bias": bias, "weights": weights}, indent=2))
    print(f"Wrote {weights_path}")
    print(f"Wrote {metrics_path}")
    print(f"Wrote {args.ts_out}")


if __name__ == "__main__":
    main()
