/** Auto-generated by python/train.py — do not edit by hand. */
export const TRAINED_MODEL_ID = "bridge-risk-logit-sklearn-v1" as const;

export const TRAINED_WEIGHTS = {
  bias: -2.42033,
  logAmount: 0.253081,
  velocity10m: 0.37677,
  highValue: 0.635888,
  veryHighValue: 0.495925,
  suspiciousMerchant: 0.629166,
  offHours: 0.209717,
  newDevice: 0.429631,
  ipRisk: 0.790312,
  nonNgContext: 0.176682,
} as const;
